### ISSUE TITLE
vehicle.poll_sensors keeps throwing up AssertionError when used in glutIdleFunc()

### ISSUE THREAD

**Issue by Hamza-B1** [BeamNG/BeamNGpy#136]
# Info
I am using `beamngpy 1.20` with `BeamNG.tech v0.22.2.0` and I have installed an unofficial PyOpenGL binary (`PyOpenGL-3.1.5-cp39-cp39-win_amd64.whl` from [here](https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyopengl)) as the one installed by pip was causing another error (`OpenGL.error.NullFunctionError`). I am using the code from the examples in the repository [here](https://github.com/BeamNG/BeamNGpy/blob/master/examples/lidar_tour.py)

# Code
```py
import mmap
import random
import sys
from time import sleep
from OpenGL.GL import *
from OpenGL.GLU import *
from OpenGL.GLUT import *
import numpy as np
from beamngpy import BeamNGpy, Scenario, Vehicle, setup_logging
from beamngpy.sensors import Lidar
from beamngpy.visualiser import LidarVisualiser

SIZE = 1024


def lidar_resize(width, height):
    if height == 0:
        height = 1

    glViewport(0, 0, width, height)


def open_window(width, height):
    glutInit()
    glutInitDisplayMode(GLUT_RGBA | GLUT_DOUBLE)
    glutInitWindowSize(width, height)
    window = glutCreateWindow(b'Lidar Tour')
    lidar_resize(width, height)
    return window


def main():
    random.seed(1703)
    setup_logging()

    beamng = BeamNGpy('localhost', 64256, home=r"C:\BeamNG.tech")
    bng = beamng.open(launch=True)

    scenario = Scenario('west_coast_usa', name="Example")

    vehicle = Vehicle('ego_vehicle', model='etk800')

    lidar = Lidar(offset=(0, 0, 1.6))
    vehicle.attach_sensor('lidar', lidar)

    scenario.add_vehicle(vehicle, pos=(-717.121, 101, 118.675),
                         rot=None, rot_quat=(0, 0, 0.3826834, 0.9238795))
    scenario.make(bng)

    window = open_window(SIZE, SIZE)
    lidar_vis = LidarVisualiser(Lidar.max_points)
    lidar_vis.open(SIZE, SIZE)

    bng.set_deterministic()
    bng.set_steps_per_second(60)

    bng.load_scenario(scenario)
    bng.hide_hud()
    bng.start_scenario()

    vehicle.ai_set_mode('span')
    vehicle.ai_drive_in_lane(True)

    def update():
        vehicle.poll_sensors()
        points = lidar.data['points']
        bng.step(3, wait=False)
        lidar_vis.update_points(points, vehicle.state)
        glutPostRedisplay()

    glutReshapeFunc(lidar_resize)
    glutIdleFunc(update)
    glutMainLoop()
    sleep(60)
    bng.close()


if __name__ == '__main__':
    main()
```
When I run this, I get an error: 
```diff
- Traceback (most recent call last):
-  File "C:\dev\Projects\pydrive\venv\lib\site-packages\OpenGL\GLUT\special.py", line 130, in safeCall
-   return function( *args, **named )
-  File "C:\dev\Projects\pydrive\main.py", line 65, in update
-    vehicle.poll_sensors()
-  File "C:\dev\Projects\pydrive\venv\lib\site-packages\beamngpy\vehicle.py", line 347, in poll_sensors
-    assert response['type'] == 'SensorData'
-AssertionError
-GLUT Idle callback <function main.<locals>.update at 0x00000214CF2E4670> with (),{} failed: returning None 

-Process finished with exit code 1
````
I have tried downgrading to beamngpy 1.19 and have had the same issue. I am using Pycharm Professional with `Python 3.9` and a virtual environment set up by the IDE.

**Comment by pascale-commits** [comment]
Hi! Thanks for reporting this issue. I've [commited a fix](https://github.com/BeamNG/BeamNGpy/commit/5294772e7f18f704abe3ca482a761572690bd296), if you want to use this code with your current setup change `bng.step(3, wait=False)` to `bng.step(3, wait=True)`.
