### ISSUE TITLE
Broken Log message

### ISSUE THREAD

**Issue by alessiogambi** [BeamNG/BeamNGpy#153]
When detaching camera sensors I see on the console a lot of warning/error messages like the one posted below, suggesting that logger might not be called appropriately?

```
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\gambitemp\AppData\Local\Programs\Python\Python37\lib\logging\__init__.py", line 1025, in emit
    msg = self.format(record)
  File "C:\Users\gambitemp\AppData\Local\Programs\Python\Python37\lib\logging\__init__.py", line 869, in format
    return fmt.format(record)
  File "C:\Users\gambitemp\AppData\Local\Programs\Python\Python37\lib\logging\__init__.py", line 608, in format
    record.message = record.getMessage()
  File "C:\Users\gambitemp\AppData\Local\Programs\Python\Python37\lib\logging\__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
....
  File "Y:\sbst-tool-competition\.venv\lib\site-packages\beamngpy\sensors.py", line 576, in detach
    f'{self.annotation_handle}')
```

**Comment by aivora-beamng** [comment]
Fixed in BeamNGpy v1.22 (https://pypi.org/project/beamngpy/1.22/).
