### ISSUE TITLE
camera doern't work in windows os,beamngpy=1.28,beamng.tech=0.31.3.0

### ISSUE THREAD

**Issue by lsm2842035890** [BeamNG/BeamNGpy#266]
def set_scripts():
    bng = BeamNGpy('localhost', 64256, home=r'E:\BeamNG\BeamNG.tech.v0.31.3.0',
                   user=r'E:\pycharmcode\pythonProject\beamng1')
    bng.open()
    scenario = Scenario('smallgrid', 'custom_road_network')
    # 创建道路网络
    # create a decal road
    road_a = Road('track_editor_C_center', rid='center_road', looped=False)
    road_a.add_nodes(
        (0, 300, 0, 6),
        (0, 400, 0, 6),
        (0, 500, 0, 6),
        (0, 600, 0, 6),
        (0, 700, 0, 6),
    )
    scenario.add_road(road_a)

    vehicle = Vehicle('ego_vehicle', model='etk800')
    vehicle1 = Vehicle('bv', model='etk800')
    scenario.add_vehicle(vehicle, pos=(0, 300, 0), rot_quat=(0, 0, 1, 0))
    scenario.add_vehicle(vehicle1, pos=(0, 307, 0), rot_quat=(0, 0, 1, 0))
    # positions = [(0, 400, 0), (0, 500, 0), (0, 600, 0)]
    # scales = [(1, 1, 1)] * 3
    # ids = ['my_waypoint_1', 'my_waypoint_2', 'my_waypoint_3']
    # scenario.add_checkpoints(positions, scales, ids)
    annotations = bng.camera.get_annotations()  # Gets a dictionary of RGB colours, indexed by material names.
    print('Annotation data: ', annotations)
    class_data = bng.camera.get_annotation_classes(annotations)  # Gets a dictionary of material names, indexed by RGB colours (encoded as 32-bit).
    print('Annotation class data: ', class_data)
    # 设置摄像机
    cam1 = Camera('camera1', bng, vehicle1,
                  requested_update_time=1, update_priority=1, is_using_shared_memory=False,
                  pos=(-0.3, 1, 2), dir=(0, 1, 0), field_of_view_y=70,
                  near_far_planes=(0.1, 100), resolution=(1024, 1024),
                  is_render_annotations=True, is_render_instance=True, is_render_depth=True)

    scripts = generate_scripts()
    scenario.make(bng)
    bng.scenario.load(scenario)
    bng.ui.hide_hud()
    bng.scenario.start()
    bng.switch_vehicle(vehicle1)
    vehicle.ai.set_speed(50, 'set')
    # vehicle.set_velocity(10,5)
    # time.sleep(10)
    # vehicle.ai.set_line(scripts)\
    # vehicle.ai.set_mode('manual')
    vehicle.ai.execute_script(scripts)
    for i in range(2):
        vehicle1.control(throttle=0.1, steering=0)
        #显示摄像头读数
        images = cam1.get_full_poll_request()
        fig, ax = plt.subplots(1, 4, figsize=(30, 30))
        ax[0].imshow(np.asarray(images['colour'].convert('RGB')))
        ax[1].imshow(np.asarray(images['annotation'].convert('RGB')))
        ax[2].imshow(np.asarray(images['instance'].convert('RGB')))
        ax[3].imshow(np.asarray(images['depth'].convert('RGB')))
        plt.show()

        bng.control.step(60)
    input('Hit enter when done...')

def generate_scripts():
    script = [
        {'x': 0, 'y': 300, 'z': 0.3, 't': 0},
        {'x': 0, 'y': 400, 'z': 0.3, 't': 5},
        {'x': 0, 'y': 500, 'z': 0.3, 't': 10},
        {'x': 0, 'y': 600, 'z': 0.3, 't': 15}
    ]
    return script

error:Traceback (most recent call last):
  File "E:\pycharmcode\pythonProject\beamng\beamng_test.py", line 581, in <module>
    set_scripts()
  File "E:\pycharmcode\pythonProject\beamng\beamng_test.py", line 292, in set_scripts
    cam1 = Camera('camera1', bng, vehicle1,
  File "C:\Users\28420\.conda\envs\beamng\lib\site-packages\beamngpy\sensors\camera\camera.py", line 173, in __init__
    self._open_camera(
  File "C:\Users\28420\.conda\envs\beamng\lib\site-packages\beamngpy\sensors\camera\camera.py", line 682, in _open_camera
    self.send_ack_ge(type='OpenCamera', ack='OpenedCamera', **data)
  File "C:\Users\28420\.conda\envs\beamng\lib\site-packages\beamngpy\connection\comm_base.py", line 85, in send_ack_ge
    CommBase._send_ack(self.bng.connection, type, ack=ack, **kwargs)
  File "C:\Users\28420\.conda\envs\beamng\lib\site-packages\beamngpy\connection\comm_base.py", line 43, in _send_ack
    response.ack(ack)
  File "C:\Users\28420\.conda\envs\beamng\lib\site-packages\beamngpy\connection\connection.py", line 275, in ack
    message = self.recv()
  File "C:\Users\28420\.conda\envs\beamng\lib\site-packages\beamngpy\connection\connection.py", line 269, in recv
    raise message
beamngpy.logging.BNGError: [string "lua/ge/extensions/tech/techCore.lua"]:1152: attempt to index a nil value

**Comment by lsm2842035890** [comment]
i got it work
