### ISSUE TITLE
ModuleNotFoundError: No module named 'pyscaffold.integration'

### ISSUE THREAD

**Issue by masskro0** [BeamNG/BeamNGpy#80]
```pip install beamngpy```  in Powershell gives me the error: 
ERROR: Command errored out with exit status 1:
     command: 'd:\paper\fuel_consumption\venv\scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\MaSSK\\AppData\\Local\\Temp\\pip-install-kmfukoz1\\beamngpy\\setup.py'"'"'; __file__='"'"'C:\\Users\\MaSSK\\AppData\\Local\\Temp\\pip-install-kmfukoz1\\beamngpy\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\MaSSK\AppData\Local\Temp\pip-pip-egg-info-oeahn9ce'
         cwd: C:\Users\MaSSK\AppData\Local\Temp\pip-install-kmfukoz1\beamngpy\
    Complete output (25 lines):
    d:\paper\fuel_consumption\venv\lib\site-packages\setuptools\pep425tags.py:89: RuntimeWarning: Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
      warn=(impl == 'cp')):
    d:\paper\fuel_consumption\venv\lib\site-packages\setuptools\pep425tags.py:93: RuntimeWarning: Config variable 'WITH_PYMALLOC' is unset, Python ABI tag may be incorrect
      warn=(impl == 'cp')):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\MaSSK\AppData\Local\Temp\pip-install-kmfukoz1\beamngpy\setup.py", line 20, in <module>
        setup_package()
      File "C:\Users\MaSSK\AppData\Local\Temp\pip-install-kmfukoz1\beamngpy\setup.py", line 16, in setup_package
        use_pyscaffold=True)
      File "d:\paper\fuel_consumption\venv\lib\site-packages\setuptools\__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "D:\Program Files (x86)\Python\lib\distutils\core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "d:\paper\fuel_consumption\venv\lib\site-packages\setuptools\dist.py", line 372, in __init__
        _Distribution.__init__(self, attrs)
      File "D:\Program Files (x86)\Python\lib\distutils\dist.py", line 292, in __init__
        self.finalize_options()
      File "d:\paper\fuel_consumption\venv\lib\site-packages\setuptools\dist.py", line 528, in finalize_options
        ep.load()(self, ep.name, value)
      File "d:\paper\fuel_consumption\venv\lib\site-packages\pkg_resources\__init__.py", line 2324, in load
        return self.resolve()
      File "d:\paper\fuel_consumption\venv\lib\site-packages\pkg_resources\__init__.py", line 2330, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
    ModuleNotFoundError: No module named 'pyscaffold.integration'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

Fix: running ```pip install PyScaffold``` to install PyScaffold before installing beamngpy.
Python version: 3.7.0
Pip version: 20.2.4
Windows version: 10

**Comment by Palculator** [comment]
Should be fixed as of v1.19.1 as `pyscaffold` is no longer referenced at all.
